// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: mess.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cupo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cupos string `protobuf:"bytes,1,opt,name=cupos,proto3" json:"cupos,omitempty"`
}

func (x *Cupo) Reset() {
	*x = Cupo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mess_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cupo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cupo) ProtoMessage() {}

func (x *Cupo) ProtoReflect() protoreflect.Message {
	mi := &file_mess_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cupo.ProtoReflect.Descriptor instead.
func (*Cupo) Descriptor() ([]byte, []int) {
	return file_mess_proto_rawDescGZIP(), []int{0}
}

func (x *Cupo) GetCupos() string {
	if x != nil {
		return x.Cupos
	}
	return ""
}

type Recepcion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok string `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *Recepcion) Reset() {
	*x = Recepcion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mess_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recepcion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recepcion) ProtoMessage() {}

func (x *Recepcion) ProtoReflect() protoreflect.Message {
	mi := &file_mess_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recepcion.ProtoReflect.Descriptor instead.
func (*Recepcion) Descriptor() ([]byte, []int) {
	return file_mess_proto_rawDescGZIP(), []int{1}
}

func (x *Recepcion) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

type Rechazado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rechazados string `protobuf:"bytes,1,opt,name=rechazados,proto3" json:"rechazados,omitempty"`
}

func (x *Rechazado) Reset() {
	*x = Rechazado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mess_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rechazado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rechazado) ProtoMessage() {}

func (x *Rechazado) ProtoReflect() protoreflect.Message {
	mi := &file_mess_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rechazado.ProtoReflect.Descriptor instead.
func (*Rechazado) Descriptor() ([]byte, []int) {
	return file_mess_proto_rawDescGZIP(), []int{2}
}

func (x *Rechazado) GetRechazados() string {
	if x != nil {
		return x.Rechazados
	}
	return ""
}

var File_mess_proto protoreflect.FileDescriptor

var file_mess_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72,
	0x70, 0x63, 0x22, 0x1c, 0x0a, 0x04, 0x43, 0x75, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x75,
	0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x75, 0x70, 0x6f, 0x73,
	0x22, 0x1b, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x65, 0x70, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x2b, 0x0a,
	0x09, 0x52, 0x65, 0x63, 0x68, 0x61, 0x7a, 0x61, 0x64, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65,
	0x63, 0x68, 0x61, 0x7a, 0x61, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x65, 0x63, 0x68, 0x61, 0x7a, 0x61, 0x64, 0x6f, 0x73, 0x32, 0x7c, 0x0a, 0x10, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x31,
	0x0a, 0x10, 0x43, 0x75, 0x70, 0x6f, 0x73, 0x44, 0x69, 0x73, 0x70, 0x6f, 0x6e, 0x69, 0x62, 0x6c,
	0x65, 0x73, 0x12, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x75, 0x70, 0x6f, 0x1a, 0x0f,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x70, 0x63, 0x69, 0x6f, 0x6e, 0x22,
	0x00, 0x12, 0x35, 0x0a, 0x0f, 0x43, 0x75, 0x70, 0x6f, 0x73, 0x52, 0x65, 0x63, 0x68, 0x61, 0x7a,
	0x61, 0x64, 0x6f, 0x73, 0x12, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x63, 0x68,
	0x61, 0x7a, 0x61, 0x64, 0x6f, 0x1a, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x63,
	0x65, 0x70, 0x63, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x65, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x2f, 0x74,
	0x64, 0x69, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mess_proto_rawDescOnce sync.Once
	file_mess_proto_rawDescData = file_mess_proto_rawDesc
)

func file_mess_proto_rawDescGZIP() []byte {
	file_mess_proto_rawDescOnce.Do(func() {
		file_mess_proto_rawDescData = protoimpl.X.CompressGZIP(file_mess_proto_rawDescData)
	})
	return file_mess_proto_rawDescData
}

var file_mess_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mess_proto_goTypes = []interface{}{
	(*Cupo)(nil),      // 0: grpc.Cupo
	(*Recepcion)(nil), // 1: grpc.Recepcion
	(*Rechazado)(nil), // 2: grpc.Rechazado
}
var file_mess_proto_depIdxs = []int32{
	0, // 0: grpc.ServidorRegional.CuposDisponibles:input_type -> grpc.Cupo
	2, // 1: grpc.ServidorRegional.CuposRechazados:input_type -> grpc.Rechazado
	1, // 2: grpc.ServidorRegional.CuposDisponibles:output_type -> grpc.Recepcion
	1, // 3: grpc.ServidorRegional.CuposRechazados:output_type -> grpc.Recepcion
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mess_proto_init() }
func file_mess_proto_init() {
	if File_mess_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mess_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cupo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mess_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recepcion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mess_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rechazado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mess_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mess_proto_goTypes,
		DependencyIndexes: file_mess_proto_depIdxs,
		MessageInfos:      file_mess_proto_msgTypes,
	}.Build()
	File_mess_proto = out.File
	file_mess_proto_rawDesc = nil
	file_mess_proto_goTypes = nil
	file_mess_proto_depIdxs = nil
}
